# These are supported funding model platforms

github: krich11
ko_fi: krich11
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# custom: ['https://your-custom-link.com']
